# Generated by Django 3.2 on 2021-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='region',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='slug',
        ),
        migrations.AddField(
            model_name='meal',
            name='img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='portrayed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
