# Generated by Django 3.2 on 2021-04-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_app', '0003_auto_20210409_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('air_date', models.CharField(blank=True, max_length=50, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('quote', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
